# Generated by Django 5.2.17 on 2026-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_default_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
