# Generated by Django 5.2.17 on 2026-09-18 04:43

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_logincode_options_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
