# Generated by Django 5.2.17 on 2026-09-20 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('points_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField(help_text='Points available to spend.')),
                ('label', models.CharField(blank=True, help_text='E.g. "Smart Shopper points" or the voucher title.', max_length=255)),
                ('expires_at', models.DateField(blank=True, help_text='Date the points lapse, printed on the slip.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(blank=True, db_column='receipt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_points', to='core.receipt')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_points', to='core.store')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='core_loyalt_user_id_e15039_idx')],
            },
        ),
    ]
