# Generated by Django 5.2.17 on 2026-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_loyaltypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemini_key_encrypted',
            field=models.TextField(blank=True, default='', editable=False, help_text="The user's own Gemini API key (BYOK), Fernet-encrypted at rest."),
        ),
    ]
