# Generated by Django 5.2.17 on 2026-09-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_gemini_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Store branch as printed, e.g. "Sandton City 1049".', max_length=160),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cashier_name',
            field=models.CharField(blank=True, help_text='Cashier/teller name printed on the slip.', max_length=120),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment line as printed, e.g. "Visa ••1234" or "Cash".', max_length=60),
        ),
        migrations.AddField(
            model_name='receipt',
            name='slip_number',
            field=models.CharField(blank=True, help_text='Transaction/invoice/slip number printed on the slip.', max_length=80),
        ),
    ]
