# Generated by Django 5.2.17 on 2026-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_receipt_branch_name_receipt_cashier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='original_text',
            field=models.TextField(blank=True, help_text='Verbatim line-by-line transcription of the slip as printed (proof-of-purchase for returns). Lines joined with newlines.'),
        ),
    ]
