# Generated by Django 5.2.17 on 2026-09-20 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_receipt_original_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('budget_80', 'Spent 80% of budget'), ('budget_100', 'Over budget'), ('points_7day', 'Points expire within 7 days'), ('points_1day', 'Points expire within 1 day')], max_length=20)),
                ('period', models.CharField(blank=True, help_text='YYYY-MM for budget alerts; blank for points alerts.', max_length=7)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'period'), name='uniq_alert_per_period')],
            },
        ),
    ]
