# Generated by Django 5.2.17 on 2026-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_budgetalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetalert',
            name='kind',
            field=models.CharField(choices=[('budget_50', 'Spent 50% of budget'), ('budget_80', 'Spent 80% of budget'), ('budget_100', 'Over budget'), ('points_7day', 'Points expire within 7 days'), ('points_1day', 'Points expire within 1 day')], max_length=20),
        ),
    ]
