# Generated by Django 5.2.17 on 2026-09-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_budgetalert_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp of the most recent successful sign-in.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total successful sign-ins across every channel (password, email/SMS/WhatsApp code, Apple).'),
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('password', 'Password'), ('email_code', 'Email code'), ('sms_code', 'SMS code'), ('whatsapp_code', 'WhatsApp code'), ('apple', 'Apple')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login audit entry',
                'verbose_name_plural': 'login audit entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
