# Generated by Django 5.2.17 on 2026-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_last_login_at_user_login_count_loginaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Throwaway guest session — usable immediately, claimable into a full account (email + password) without losing any data.'),
        ),
        migrations.AlterField(
            model_name='loginaudit',
            name='method',
            field=models.CharField(choices=[('password', 'Password'), ('email_code', 'Email code'), ('sms_code', 'SMS code'), ('whatsapp_code', 'WhatsApp code'), ('apple', 'Apple'), ('guest', 'Guest')], max_length=20),
        ),
    ]
